tinymce.addI18n('si',{
"Redo": "නැවත කරන්න",
"Undo": "අහෝසි කරන්න",
"Cut": "කපාගන්න",
"Copy": "පිටපත් කරන්න",
"Paste": "අලවන්න",
"Select all": "සියල්ල තෝරන්න",
"New document": "නව ලේඛනය",
"Ok": "හරි",
"Cancel": "අවලංගු කරන්න",
"Visual aids": "දෘශ්‍ය ආධාරක",
"Bold": "තද අකුරු",
"Italic": "ඇල අකුරු",
"Underline": "යටි ඉරි",
"Strikethrough": "මැද ඉරි",
"Superscript": "සුපර්ස්ක්‍රිප්ට්",
"Subscript": "සබ්ස්ක්‍රිප්ට්",
"Clear formatting": "ආකෘතිකරණය ඉවත් කරන්න",
"Align left": "වමට පෙළගස්වන්න",
"Align center": "මැදට පෙළගස්වන්න",
"Align right": "දකුණට පෙළගස්වන්න",
"Justify": "සාධාරණීකරණය කරන්න",
"Bullet list": "බුලට් ලැයිස්තුව",
"Numbered list": "අංකිත ලැයිස්තුව",
"Decrease indent": "අඩංගු කිරීම අඩු කරන්න",
"Increase indent": "අඩංගු කිරීම වැඩි කරන්න",
"Close": "වසා දමන්න",
"Formats": "ආකෘති",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "ඔබගේ බ්‍රවුසරය ක්ලිප්බෝඩ් වෙත සෘජු ප්‍රවේශයට සහාය නොදක්වයි. කරුණාකර Ctrl+X\/C\/V යතුරුපුවරු කෙටිමං භාවිතා කරන්න.",
"Headers": "ශීර්ෂයන්",
"Header 1": "ශීර්ෂය 1",
"Header 2": "ශීර්ෂය 2",
"Header 3": "ශීර්ෂය 3",
"Header 4": "ශීර්ෂය 4",
"Header 5": "ශීර්ෂය 5",
"Header 6": "ශීර්ෂය 6",
"Headings": "ශීර්ෂයන්",
"Heading 1": "ශීර්ෂය 1",
"Heading 2": "ශීර්ෂය 2",
"Heading 3": "ශීර්ෂය 3",
"Heading 4": "ශීර්ෂය 4",
"Heading 5": "ශීර්ෂය 5",
"Heading 6": "ශීර්ෂය 6",
"Preformatted": "පෙර ආකෘතිගත කරන ලදී",
"Div": "Div",
"Pre": "පූර්ව",
"Code": "කේතය",
"Paragraph": "ඡේදය",
"Blockquote": "බ්ලොක් උපුටා ගැනීම",
"Inline": "ඉන්ලයින්",
"Blocks": "බ්ලොක්",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "අලවන්න දැන් සරල පෙළ මාදිලියේ ඇත. ඔබ මෙම විකල්පය අක්‍රිය කරන තුරු අන්තර්ගතය සරල පෙළ ලෙස අලවනු ඇත.",
"Fonts": "අකුරු",
"Font Sizes": "අකුරු ප්‍රමාණ",
"Class": "පංතිය",
"Browse for an image": "රූපයක් සඳහා සොයන්න",
"OR": "හෝ",
"Drop an image here": "රූපයක් මෙතැනට අදින්න",
"Upload": "උඩුගත කරන්න",
"Block": "බ්ලොක්",
"Align": "පෙළගස්වන්න",
"Default": "පෙරනිමි",
"Circle": "වෘත්තය",
"Disc": "තැටිය",
"Square": "හතරැස්",
"Lower Alpha": "පහළ ඇල්ෆා",
"Lower Greek": "පහළ ග්‍රීක",
"Lower Roman": "පහළ රෝමන්",
"Upper Alpha": "ඉහළ ඇල්ෆා",
"Upper Roman": "ඉහළ රෝමන්",
"Anchor...": "ඇන්කර්...",
"Name": "නම",
"Id": "හැඳුනුම",
"Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "හැඳුනුම අකුරකින් ආරම්භ විය යුතු අතර, ඉන්පසු අකුරු, ඉලක්කම්, ඉරි, තිත්, තීරු හෝ යටි ඉරි පමණක් අඩංගු විය යුතුය.",
"You have unsaved changes are you sure you want to navigate away?": "ඔබට සුරැකූ වෙනස්කම් නොමැත, ඔබට ඉවත්ව යාමට අවශ්‍ය බව විශ්වාසද?",
"Restore last draft": "අවසාන කෙටුම්පත ප්‍රතිස්ථාපනය කරන්න",
"Special character...": "විශේෂ අක්ෂර...",
"Source code": "මූල කේතය",
"Insert\/Edit code sample": "කේත නියැදියක් ඇතුල් කරන්න\/සංස්කරණය කරන්න",
"Language": "භාෂාව",
"Code sample...": "කේත නියැදිය...",
"Color Picker": "වර්ණ තෝරනය",
"R": "රතු",
"G": "කොළ",
"B": "නිල්",
"Left to right": "වමේ සිට දකුණට",
"Right to left": "දකුණේ සිට වමට",
"Emoticons...": "ඉමොටිකෝන...",
"Metadata and Document Properties": "මෙටාදත්ත සහ ලේඛන ගුණාංග",
"Title": "ශීර්ෂය",
"Keywords": "මූල පද",
"Description": "විස්තරය",
"Robots": "රොබෝවරු",
"Author": "කර්තෘ",
"Encoding": "කේතනය",
"Fullscreen": "සම්පූර්ණ තිරය",
"Action": "ක්‍රියාව",
"Shortcut": "කෙටිමඟ",
"Help": "උදව්",
"Address": "ලිපිනය",
"Focus to menubar": "මෙනු තීරුව වෙත අවධානය යොමු කරන්න",
"Focus to toolbar": "මෙවලම් තීරුව වෙත අවධානය යොමු කරන්න",
"Focus to element path": "අංග මාර්ගය වෙත අවධානය යොමු කරන්න",
"Focus to contextual toolbar": "සන්දර්භීය මෙවලම් තීරුව වෙත අවධානය යොමු කරන්න",
"Insert link (if link plugin activated)": "සම්බන්ධකයක් ඇතුල් කරන්න (සම්බන්ධක ප්ලගිනය සක්‍රිය නම්)",
"Save (if save plugin activated)": "සුරකින්න (සුරැකීමේ ප්ලගිනය සක්‍රිය නම්)",
"Find (if searchreplace plugin activated)": "සොයන්න (සොයන්න-ප්‍රතිස්ථාපන ප්ලගිනය සක්‍රිය නම්)",
"Plugins installed ({0}):": "ප්ලගින ස්ථාපනය කර ඇත ({0}):",
"Premium plugins:": "වාරික ප්ලගින:",
"Learn more...": "තව දැනගන්න...",
"You are using {0}": "ඔබ {0} භාවිතා කරයි",
"Plugins": "ප්ලගින",
"Handy Shortcuts": "පහසු කෙටිමං",
"Horizontal line": "තිරස් රේඛාව",
"Insert\/edit image": "රූපයක් ඇතුල් කරන්න\/සංස්කරණය කරන්න",
"Image description": "රූප විස්තරය",
"Source": "මූලාශ්‍රය",
"Dimensions": "මාන",
"Constrain proportions": "සමානුපාතිකයන් සීමා කරන්න",
"General": "සාමාන්‍ය",
"Advanced": "උසස්",
"Style": "ශෛලිය",
"Vertical space": "සිරස් ඉඩ",
"Horizontal space": "තිරස් ඉඩ",
"Border": "සීමාව",
"Insert image": "රූපයක් ඇතුල් කරන්න",
"Image...": "රූපය...",
"Image list": "රූප ලැයිස්තුව",
"Rotate counterclockwise": "වමාවර්තව කරකවන්න",
"Rotate clockwise": "දක්ෂිණාවර්තව කරකවන්න",
"Flip vertically": "සිරස් අතට පෙරළන්න",
"Flip horizontally": "තිරස් අතට පෙරළන්න",
"Edit image": "රූපය සංස්කරණය කරන්න",
"Image options": "රූප විකල්ප",
"Zoom in": "විශාල කරන්න",
"Zoom out": "කුඩා කරන්න",
"Crop": "කප්පාදු කරන්න",
"Resize": "ප්‍රමාණය වෙනස් කරන්න",
"Orientation": "දිශානතිය",
"Brightness": "දීප්තිය",
"Sharpen": "තියුණු කරන්න",
"Contrast": "විරුද්ධත්වය",
"Color levels": "වර්ණ මට්ටම්",
"Gamma": "ගැමා",
"Invert": "ප්‍රතිලෝම කරන්න",
"Apply": "යොදන්න",
"Back": "ආපසු",
"Insert date\/time": "දිනය\/වේලාව ඇතුල් කරන්න",
"Date\/time": "දිනය\/වේලාව",
"Insert\/Edit Link": "සම්බන්ධකයක් ඇතුල් කරන්න\/සංස්කරණය කරන්න",
"Insert\/edit link": "සම්බන්ධකයක් ඇතුල් කරන්න\/සංස්කරණය කරන්න",
"Text to display": "පෙන්වීමට පෙළ",
"Url": "URL",
"Open link in...": "සම්බන්ධකය විවෘත කරන්න...",
"Current window": "වත්මන් කවුළුව",
"None": "කිසිවක් නැත",
"New window": "නව කවුළුව",
"Remove link": "සම්බන්ධකය ඉවත් කරන්න",
"Anchors": "ඇන්කර්ස්",
"Link...": "සම්බන්ධකය...",
"Paste or type a link": "සම්බන්ධකයක් අලවන්න හෝ ටයිප් කරන්න",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "ඔබ ඇතුල් කළ URL එක විද්‍යුත් තැපැල් ලිපිනයක් බව පෙනේ. අවශ්‍ය mailto: උපසර්ගය එක් කිරීමට ඔබට අවශ්‍යද?",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "ඔබ ඇතුල් කළ URL එක බාහිර සම්බන්ධකයක් බව පෙනේ. අවශ්‍ය http:\/\/ උපසර්ගය එක් කිරීමට ඔබට අවශ්‍යද?",
"Link list": "සම්බන්ධක ලැයිස්තුව",
"Insert video": "වීඩියෝවක් ඇතුල් කරන්න",
"Insert\/edit video": "වීඩියෝවක් ඇතුල් කරන්න\/සංස්කරණය කරන්න",
"Insert\/edit media": "මාධ්‍යයක් ඇතුල් කරන්න\/සංස්කරණය කරන්න",
"Alternative source": "විකල්ප මූලාශ්‍රය",
"Alternative source URL": "විකල්ප මූලාශ්‍ර URL",
"Media poster (Image URL)": "මාධ්‍ය පෝස්ටරය (රූප URL)",
"Paste your embed code below:": "ඔබේ කාවැද්දුම් කේතය පහතින් අලවන්න:",
"Embed": "කාවැද්දීම",
"Media...": "මාධ්‍ය...",
"Nonbreaking space": "නොකැඩෙන ඉඩ",
"Page break": "පිටු කැඩීම",
"Paste as text": "පෙළ ලෙස අලවන්න",
"Preview": "පෙරදසුන",
"Print...": "මුද්‍රණය...",
"Save": "සුරකින්න",
"Find": "සොයන්න",
"Replace with": "සමඟ ප්‍රතිස්ථාපනය කරන්න",
"Replace": "ප්‍රතිස්ථාපනය කරන්න",
"Replace all": "සියල්ල ප්‍රතිස්ථාපනය කරන්න",
"Previous": "පෙර",
"Next": "ඊළඟ",
"Find and replace...": "සොයන්න සහ ප්‍රතිස්ථාපනය කරන්න...",
"Could not find the specified string.": "නිශ්චිත පෙළ සොයාගත නොහැකි විය.",
"Match case": "අකුරු ගැලපීම",
"Find whole words only": "සම්පූර්ණ වචන පමණක් සොයන්න",
"Spell check": "අක්ෂර වින්‍යාසය පරීක්ෂා කරන්න",
"Ignore": "අත්හරින්න",
"Ignore all": "සියල්ල අත්හරින්න",
"Finish": "අවසන් කරන්න",
"Add to Dictionary": "ශබ්දකෝෂයට එක් කරන්න",
"Insert table": "වගුවක් ඇතුල් කරන්න",
"Table properties": "වගු ගුණාංග",
"Delete table": "වගුව මකන්න",
"Cell": "සෛලය",
"Row": "පේළිය",
"Column": "තීරුව",
"Cell properties": "සෛල ගුණාංග",
"Merge cells": "සෛල ඒකාබද්ධ කරන්න",
"Split cell": "සෛල බෙදන්න",
"Insert row before": "පෙර පේළියක් ඇතුල් කරන්න",
"Insert row after": "පසු පේළියක් ඇතුල් කරන්න",
"Delete row": "පේළිය මකන්න",
"Row properties": "පේළි ගුණාංග",
"Cut row": "පේළිය කපාගන්න",
"Copy row": "පේළිය පිටපත් කරන්න",
"Paste row before": "පෙර පේළිය අලවන්න",
"Paste row after": "පසු පේළිය අලවන්න",
"Insert column before": "පෙර තීරුවක් ඇතුල් කරන්න",
"Insert column after": "පසු තීරුවක් ඇතුල් කරන්න",
"Delete column": "තීරුව මකන්න",
"Cols": "තීරු",
"Rows": "පේළි",
"Width": "පළල",
"Height": "උස",
"Cell spacing": "සෛල අතර ඉඩ",
"Cell padding": "සෛල පිරවීම",
"Show caption": "විස්තරය පෙන්වන්න",
"Left": "වම",
"Center": "මැද",
"Right": "දකුණ",
"Cell type": "සෛල වර්ගය",
"Scope": "විෂය පථය",
"Alignment": "පෙළගැස්ම",
"H Align": "තිරස් පෙළගැස්ම",
"V Align": "සිරස් පෙළගැස්ම",
"Top": "ඉහළ",
"Middle": "මැද",
"Bottom": "පහළ",
"Header cell": "ශීර්ෂ සෛලය",
"Row group": "පේළි කණ්ඩායම",
"Column group": "තීරු කණ්ඩායම",
"Row type": "පේළි වර්ගය",
"Header": "ශීර්ෂය",
"Body": "ශරීරය",
"Footer": "පාදකය",
"Border color": "සීමාවේ වර්ණය",
"Insert template...": "සැකිල්ලක් ඇතුල් කරන්න...",
"Templates": "සැකිලි",
"Template": "සැකිල්ල",
"Text color": "පෙළ වර්ණය",
"Background color": "පසුබිම් වර්ණය",
"Custom...": "අභිරුචි...",
"Custom color": "අභිරුචි වර්ණය",
"No color": "වර්ණයක් නැත",
"Remove color": "වර්ණය ඉවත් කරන්න",
"Table of Contents": "අන්තර්ගත වගුව",
"Show blocks": "බ්ලොක් පෙන්වන්න",
"Show invisible characters": "නොපෙනෙන අක්ෂර පෙන්වන්න",
"Word count": "වචන ගණන",
"Count": "ගණන",
"Document": "ලේඛනය",
"Selection": "තෝරාගැනීම",
"Words": "වචන",
"Words: {0}": "වචන: {0}",
"{0} words": "{0} වචන",
"File": "ගොනුව",
"Edit": "සංස්කරණය",
"Insert": "ඇතුල් කරන්න",
"View": "දසුන",
"Format": "ආකෘතිය",
"Table": "වගුව",
"Tools": "මෙවලම්",
"Powered by {0}": "{0} විසින් බලගන්වන ලදී",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "සමෘද්ධිමත් පෙළ ප්‍රදේශය. මෙනුව සඳහා ALT-F9 ඔබන්න. මෙවලම් තීරුව සඳහා ALT-F10 ඔබන්න. උදව් සඳහා ALT-0 ඔබන්න",
"Image title": "රූපයේ ශීර්ෂය",
"Border width": "සීමාවේ පළල",
"Border style": "සීමාවේ ශෛලිය",
"Error": "දෝෂය",
"Warn": "අවවාදය",
"Valid": "වලංගුයි",
"To open the popup, press Shift+Enter": "පොප්අප් එක විවෘත කිරීමට, Shift+Enter ඔබන්න",
"Rich Text Area. Press ALT-0 for help.": "සමෘද්ධිමත් පෙළ ප්‍රදේශය. උදව් සඳහා ALT-0 ඔබන්න.",
"System Font": "පද්ධති අකුරු",
"Failed to upload image: {0}": "රූපය උඩුගත කිරීම අසාර්ථක විය: {0}",
"Failed to load plugin: {0} from url {1}": "URL {1} වෙතින් ප්ලගිනය: {0} පැටවීම අසාර්ථක විය",
"Failed to load plugin url: {0}": "ප්ලගින URL එක පැටවීම අසාර්ථක විය: {0}",
"Failed to initialize plugin: {0}": "ප්ලගිනය ආරම්භ කිරීම අසාර්ථක විය: {0}",
"example": "උදාහරණය",
"Search": "සොයන්න",
"All": "සියල්ල",
"Currency": "මුදල්",
"Text": "පෙළ",
"Quotations": "උපුටා දැක්වීම්",
"Mathematical": "ගණිතමය",
"Extended Latin": "දිගු ලතින්",
"Symbols": "සංකේත",
"Arrows": "ඊතල",
"User Defined": "පරිශීලක අර්ථ දක්වා ඇත",
"dollar sign": "ඩොලර් සලකුණ",
"currency sign": "මුදල් සලකුණ",
"euro-currency sign": "යුරෝ මුදල් සලකුණ",
"colon sign": "තීරු සලකුණ",
"cruzeiro sign": "ක්‍රුසෙයිරෝ සලකුණ",
"french franc sign": "ප්‍රංශ ෆ්රෑන්ක් සලකුණ",
"lira sign": "ලීරා සලකුණ",
"mill sign": "මිල් සලකුණ",
"naira sign": "නයිරා සලකුණ",
"peseta sign": "පෙසෙටා සලකුණ",
"rupee sign": "රුපියල් සලකුණ",
"won sign": "වොන් සලකුණ",
"new sheqel sign": "නව ෂෙකල් සලකුණ",
"dong sign": "ඩොං සලකුණ",
"kip sign": "කිප් සලකුණ",
"tugrik sign": "තුග්‍රික් සලකුණ",
"drachma sign": "ඩ්‍රැක්මා සලකුණ",
"german penny symbol": "ජර්මානු පෙනි සංකේතය",
"peso sign": "පෙසෝ සලකුණ",
"guarani sign": "ගුවරානි සලකුණ",
"austral sign": "ඕස්ට්‍රල් සලකුණ",
"hryvnia sign": "හ්‍රිව්නියා සලකුණ",
"cedi sign": "සෙඩි සලකුණ",
"livre tournois sign": "ලිව්‍රේ ටුවර්නොයිස් සලකුණ",
"spesmilo sign": "ස්පෙස්මිලෝ සලකුණ",
"tenge sign": "ටෙන්ගේ සලකුණ",
"indian rupee sign": "ඉන්දියානු රුපියල් සලකුණ",
"turkish lira sign": "තුර්කි ලීරා සලකුණ",
"nordic mark sign": "නෝර්ඩික් මාක් සලකුණ",
"manat sign": "මනාට් සලකුණ",
"ruble sign": "රූබල් සලකුණ",
"yen character": "යෙන් අක්ෂරය",
"yuan character": "යුවාන් අක්ෂරය",
"yuan character, in hong kong and taiwan": "හොංකොං සහ තායිවානයේ යුවාන් අක්ෂරය",
"yen\/yuan character variant one": "යෙන්\/යුවාන් අක්ෂර ප්‍රභේදය එක",
"Loading emoticons...": "ඉමොටිකෝන පූරණය වෙමින් පවතී...",
"Could not load emoticons": "ඉමොටිකෝන පූරණය කිරීමට නොහැකි විය",
"People": "මිනිසුන්",
"Animals and Nature": "සතුන් සහ ස්වභාවධර්මය",
"Food and Drink": "ආහාර සහ පාන",
"Activity": "ක්‍රියාකාරකම්",
"Travel and Places": "ගමන් සහ ස්ථාන",
"Objects": "වස්තූන්",
"Flags": "ධජ",
"Characters": "අක්ෂර",
"Characters (no spaces)": "අක්ෂර (හිස්තැන් නැත)",
"{0} characters": "{0} අක්ෂර",
"Error: Form submit field collision.": "දෝෂය: ආකෘති ඉදිරිපත් කිරීමේ ක්ෂේත්‍ර ගැටුම.",
"Error: No form element found.": "දෝෂය: ආකෘති අංගයක් සොයාගත නොහැකි විය.",
"Update": "යාවත්කාලීන කරන්න",
"Color swatch": "වර්ණ මාලාව",
"Turquoise": "ටර්කයිස්",
"Green": "කොළ",
"Blue": "නිල්",
"Purple": "දම්",
"Navy Blue": "නාවික නිල්",
"Dark Turquoise": "තද ටර්කයිස්",
"Dark Green": "තද කොළ",
"Medium Blue": "මධ්‍යම නිල්",
"Medium Purple": "මධ්‍යම දම්",
"Midnight Blue": "මධ්‍යම නිල්",
"Yellow": "කහ",
"Orange": "තැඹිලි",
"Red": "රතු",
"Light Gray": "ලා අළු",
"Gray": "අළු",
"Dark Yellow": "තද කහ",
"Dark Orange": "තද තැඹිලි",
"Dark Red": "තද රතු",
"Medium Gray": "මධ්‍යම අළු",
"Dark Gray": "තද අළු",
"Light Green": "ලා කොළ",
"Light Yellow": "ලා කහ",
"Light Red": "ලා රතු",
"Light Purple": "ලා දම්",
"Light Blue": "ලා නිල්",
"Dark Purple": "තද දම්",
"Dark Blue": "තද නිල්",
"Black": "කළු",
"White": "සුදු",
"Switch to or from fullscreen mode": "සම්පූර්ණ තිර මාදිලියට මාරු වන්න හෝ එයින් ඉවත් වන්න",
"Open help dialog": "උදව් කවුළුව විවෘත කරන්න",
"history": "ඉතිහාසය",
"styles": "ශෛලීන්",
"formatting": "ආකෘතිකරණය",
"alignment": "පෙළගැස්ම",
"indentation": "අඩංගු කිරීම",
"permanent pen": "ස්ථීර පෑන",
"comments": "අදහස්",
"Format Painter": "ආකෘතිය පිටපත් කරන්න",
"Insert\/edit iframe": "iframe ඇතුල් කරන්න\/සංස්කරණය කරන්න",
"Capitalization": "විශාල අකුරු භාවිතය",
"lowercase": "කුඩා අකුරු",
"UPPERCASE": "විශාල අකුරු",
"Title Case": "ශීර්ෂ වචන",
"Permanent Pen Properties": "ස්ථීර පෑන ගුණාංග",
"Permanent pen properties...": "ස්ථීර පෑන ගුණාංග...",
"Font": "අකුරු",
"Size": "ප්‍රමාණය",
"More...": "තව...",
"Spellcheck Language": "අක්ෂර වින්‍යාසය පරීක්ෂා කිරීමේ භාෂාව",
"Select...": "තෝරන්න...",
"Preferences": "අභිමතයන්",
"Yes": "ඔව්",
"No": "නැත",
"Keyboard Navigation": "යතුරුපුවරු සංචලනය",
"Version": "අනුවාදය",
"Anchor": "ඇන්කර්",
"Special character": "විශේෂ අක්ෂරය",
"Code sample": "කේත නියැදිය",
"Color": "වර්ණය",
"Emoticons": "ඉමොටිකෝන",
"Document properties": "ලේඛන ගුණාංග",
"Image": "රූපය",
"Insert link": "සම්බන්ධකයක් ඇතුල් කරන්න",
"Target": "ඉලක්කය",
"Link": "සම්බන්ධකය",
"Poster": "පෝස්ටරය",
"Media": "මාධ්‍ය",
"Print": "මුද්‍රණය",
"Prev": "පෙර",
"Find and replace": "සොයන්න සහ ප්‍රතිස්ථාපනය කරන්න",
"Whole words": "සම්පූර්ණ වචන",
"Spellcheck": "අක්ෂර වින්‍යාසය පරීක්ෂා කිරීම",
"Caption": "විස්තරය",
"Insert template": "සැකිල්ලක් ඇතුල් කරන්න"
});